# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'sample'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'sample'
    customCommand: 'run build'

- task: CopyFiles@2
  inputs:
    Contents: 'sample/build/**'
    TargetFolder: $(Build.ArtifactStagingDirectory) 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'build1'
    publishLocation: 'Container'
